font-family = Sarasa Fixed J
font-size = 20

quit-after-last-window-closed = true
copy-on-select = clipboard

# This makes (Neo)Vim key map `<C-_>`(slash) work
keybind = ctrl+/=text:\x1f
# This allows ClaudeCode prompts to use line breaks
keybind = shift+enter=text:\n
