font-family = Sarasa Fixed J
font-style = Light
font-size = 22
font-feature = -calt, -clig, -liga

theme = Relaxed

background-opacity = 0.9
background-blur = 25
unfocused-split-opacity = 0.6

quit-after-last-window-closed = true
copy-on-select = clipboard

# This makes (Neo)Vim key map `<C-_>`(slash) work
keybind = ctrl+/=text:\x1f
# This allows ClaudeCode prompts to use line breaks
keybind = shift+enter=text:\n

custom-shader = ~/Codes/ghostty-cursor-shaders/cursor_warp.glsl
custom-shader = ~/Codes/ghostty-cursor-shaders/ripple_cursor.glsl
